// Types referenced in the autogenerated Wayland protocol module.
// This file is appended directly to the autogenerated file and not `@import`ed.

/// A signed 24.8 fixed-point number
pub const Fixed = packed struct(i32) {
    decimal: u8,
    integer: i24,

    pub fn toDouble(fixed: Fixed) f64 {
        return @as(f64, @bitCast(
            ((@as(i64, 1023) + @as(i64, 44)) << 52) +
            (@as(i64, 1) << 51) +
            @as(i32, @bitCast(fixed))
        )) - @as(f64, @floatFromInt(@as(i64, 3) << 43));
    }

    pub fn fromDouble(double: f64) Fixed {
        return @bitCast(@as(i32, @truncate(@as(i64, @bitCast(
            double + @as(f64, @floatFromInt(@as(i64, 3) << (51-8)))
        )))));
    }

    pub fn toInt(fixed: Fixed) i32 {
        return @divTrunc(@as(i32, @bitCast(fixed)), 256);
    }

    pub fn fromInt(int: i32) Fixed {
        return @bitCast(int * 256);
    }
};

pub const String = struct {
    /// Length including terminating null byte (string length plus one),
    /// or 0 for `NULL`
    len: u32,
    ptr: [*:0]const u8,

    pub fn asSlice(str: String) ?[:0]const u8 {
        return if (str.len != 0) str.ptr[0..str.len-1 :0] else null;
    }
};

pub const Array = struct {
    /// Size of array contents in bytes
    size: u32,
    ptr: [*]const u8,
};

/// File descriptors are not sent directly within the corresponding message,
/// but in the ancillary data of the UNIX domain socket message (`msg_control`).
pub const FD = @import("std").posix.fd_t;
