// Types referenced in the autogenerated Wayland protocol module.
// This file is appended directly to the autogenerated file and not `@import`ed.

/// A signed 24.8 fixed-point number
pub const Fixed = packed struct(i32) {
    decimal: u8,
    integer: i24,

    /// See wayland-util.h
    pub fn toDouble(fixed: Fixed) f64 {
        return @as(f64, @bitCast(
            ((@as(i64, 1023) + @as(i64, 44)) << 52) +
            (@as(i64, 1) << 51) +
            @as(i32, @bitCast(fixed))
        )) - @as(f64, @floatFromInt(@as(i64, 3) << 43));
    }

    /// See wayland-util.h
    pub fn fromDouble(double: f64) Fixed {
        return @bitCast(@as(i32, @truncate(@as(i64, @bitCast(
            double + @as(f64, @floatFromInt(@as(i64, 3) << (51-8)))
        )))));
    }

    /// See wayland-util.h
    pub fn toInt(fixed: Fixed) i32 {
        return @divTrunc(@as(i32, @bitCast(fixed)), 256);
    }

    /// See wayland-util.h
    pub fn fromInt(int: i32) Fixed {
        return @bitCast(int * 256);
    }

    pub fn format(fixed: Fixed, w: *std.Io.Writer) std.Io.Writer.Error!void {
        try w.printInt(fixed.integer, 10, .lower, .{});
        try w.writeByte('.');
        try w.printInt(fixed.decimal, 10, .lower, .{});
    }
};

pub const String = struct {
    /// Length including terminating null byte (string length plus one).
    /// In the wire protocol, `0` indicates `NULL`,
    /// in which case the arg is parsed as a `null` `?String`,
    /// and it is asserted that a non-optional `String` view never has `len` `0`.
    len: u32,
    ptr: [*:0]const u8,

    pub fn toSlice(str: String) [:0]const u8 {
        return if (str.len > 0) str.ptr[0..str.len-1 :0] else unreachable;
    }

    pub fn fromSlice(slice: [:0]const u8) String {
        return .{
            .len = @as(u32, @intCast(slice.len)) + 1,
            .ptr = slice.ptr,
        };
    }

    pub fn format(string: String, w: *std.Io.Writer) std.Io.Writer.Error!void {
        try w.writeByte('"');
        try w.writeAll(string.toSlice());
        try w.writeByte('"');
    }
};

pub const Array = struct {
    /// Size of array contents in bytes
    size: u32,
    ptr: [*]const u8,

    pub fn format(array: Array, w: *std.Io.Writer) std.Io.Writer.Error!void {
        const max_print = 8;
        const bytes = array.ptr[0..@min(array.size, max_print)];
        try w.writeAll("{ ");
        try w.printHex(bytes, .upper);
        try w.writeByte(' ');
        if (array.size > max_print) try w.writeAll("... ");
        try w.writeByte('}');
    }
};

/// File descriptors are not sent directly within the corresponding message,
/// but in the ancillary data of the UNIX domain socket message (`msg_control`).
pub const File = struct {
    descriptor: std.posix.fd_t,
};

const std = @import("std");
